In [15]:
import torch
from PIL import Image
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
from time import sleep

# Creation of csv files using images

1. Changed directory to folder which contains images of rose
2. Stored image in an array
3. Resized it
4. Converted to numpy array
5. Flattened the image to a row vector and normalized it 
6. Reshaped to ensure that its not a rank 1 matrix
7. Vertically stacked all the vectors
8. Horizontally stacked ones coloum vector at the end. (Here 1 represents rose)
7. Stored each of them in a seperate csv file

Dataset link: https://www.kaggle.com/alxmamaev/flowers-recognition/downloads/flowers.zip/2

In [17]:
path = '/home/rohit/Desktop/flower/train' # Path for roses
os.chdir(path)

data = []
for pic in os.listdir(path):
    if pic.endswith("r.jpg"):
        im = Image.open(pic)
        im = im.resize((150,100),Image.ANTIALIAS)
        im = np.array(im)
        im = im.ravel() / 255
        im = np.append(im,[1])
        im = np.reshape(im,(1,im.size))
        data.append(im)
    elif pic.endswith("s.jpg"):
        
        
data = np.vstack(data)
data = np.hstack((data,np.ones((np.shape(data)[0],1)))) # rose = 1

dfr = pd.DataFrame(data)
np.shape(data)

(1318, 45001)

In [18]:
dfr.to_csv('rose.csv',  header = False, index = False)

In [4]:
path = '/home/rohit/Desktop/flowers/sunflower' # Path for sunflower
os.chdir(path)

data = []
for pic in os.listdir(path):
    if pic.endswith(".jpg"):
        im = Image.open(pic)
        im = im.resize((150,100),Image.ANTIALIAS)
        im = np.array(im)
        im = im.ravel() / 255
        im = np.reshape(im,(1,im.size))
        data.append(im)
        
data = np.vstack(data)
data = np.hstack((data,np.zeros((np.shape(data)[0],1)))) # sunflower = 0

dfs = pd.DataFrame(data)
dfs.head()

,0,1,2,3,4,5,6,7,8,9,...,44991,44992,44993,44994,44995,44996,44997,44998,44999,45000
0,0.125490,0.164706,0.211765,0.129412,0.160784,0.211765,0.137255,0.168627,0.223529,0.152941,...,0.168627,0.262745,0.239216,0.176471,0.254902,0.239216,0.152941,0.247059,0.215686,0.0
1,0.152941,0.345098,0.007843,0.149020,0.349020,0.003922,0.164706,0.380392,0.003922,0.180392,...,0.188235,0.200000,0.074510,0.200000,0.239216,0.043137,0.101961,0.152941,0.035294,0.0
2,0.066667,0.047059,0.007843,0.160784,0.141176,0.023529,0.160784,0.145098,0.054902,0.196078,...,0.129412,0.141176,0.043137,0.294118,0.219608,0.015686,0.533333,0.345098,0.003922,0.0
3,0.705882,0.564706,0.258824,0.698039,0.541176,0.227451,0.678431,0.501961,0.168627,0.698039,...,0.474510,0.462745,0.149020,0.482353,0.466667,0.176471,0.494118,0.478431,0.200000,0.0
4,0.705882,0.764706,0.843137,0.709804,0.772549,0.858824,0.717647,0.780392,0.874510,0.717647,...,0.596078,0.549020,0.121569,0.141176,0.105882,0.082353,0.427451,0.352941,0.007843,0.0

In [5]:
dfs.to_csv('sunflower.csv',  header = False, index = False)

In [32]:
x = np.random.rand(1,4)
x = np.append(x,[1])
x

array([0.60708876, 0.43480248, 0.53948703, 0.78122409, 1.        ])